### ISSUE TITLE
alacritty default shell

### ISSUE THREAD

**Issue by jayraghavan** [benbrastmckie/.config#22]
alacritty still comes up loading zsh. How to load fish as default shell. In the alacritty.yml, the shell for fish is specified as:
`  program: /usr/local/bin/fish
`

fish is present in `/usr/local/bin/fish` and can be launched as a shell

Also noticed that there is no tmux directory inside .config as specified in the document. The .tmux.conf file is what probably came with installation of tmux

For git, lazygit is missing.

**Comment by benbrastmckie** [comment]
Thanks for catching the missing lazygit. I've updated the README.md to include installation instructions for downloading and installing lazygit.

As Alacritty, I think the .tmux.conf file was missing from the .config/tmux folder in my repo, but I've since updated it to include the file. You will need to move the file to your home folder as specified in the README.md, and then run the following:
```
tmux kill-server
```
This will get Tmux to reload the .tmux.conf file. The next time you open Alacritty, it should run Fish as the default shell inside a Tmux window.

**Comment by jayraghavan** [comment]
Thank you! This has been very helpful overall. I have now most of the things working. I've configured two environments: on Mac (MBP), and on Linux (Pop OS - a debian variant). I can get to build latex files and generate pdf's. 

Here is a summary of outstanding issues:
1. alacritty still does not launch fish. This doesn't bother me. Alacritty always come up with the default shell specified for the user. For example in my MBP, it is zsh and on the linux it is bash. There's something wrong with the way alacritty launches a shell, the login options etc. Also I noticed that at one place in the alacritty.yml, it is not properly indented (line 279). I can always launch fish from an existing shell. I've spent a lot of time investigating this.

2. Line 2 in the .tmux.conf seems to be unnecessary. I consistently get the error "no current target". Commenting this line seems to resolve the problem

3. not clear how colors are managed. While the colors are not bad, I'd like to dim the text lettering a bit. Any idea if we can get the base16 color schemes (see: https://github.com/chriskempson/base16)

4. To get xelatex to be the default latex command, I created the file ~/.latexmkrc that has:
`$pdflatex="xelatex %O %S";`

**Comment by benbrastmckie** [comment]
No worries! 

1.  I assume you've tried what is recommended here: https://fishshell.com/docs/current/tutorial.html#switching-to-fish

2.  If by the second line in .tmux.conf you mean `bind R source ~/.tmux.conf\\; display "~/.tmux.conf sourced!"
` the purpose of this line is to add the binding `Ctrl+Space, Shift+r` for reloading the .tmux.conf file. Are you sure that the .tmux.conf file has been moved to the home folder as explained in the README.md? This would also explain why Fish is not loading.

3. I have not taken the time to mess about with the colors which come with the theme that I've installed, but there are lots of resources out there.

I have just completed writing up a [Cheat Sheet](https://github.com/benbrastmckie/.config/blob/master/CheatSheet.md) which will perhaps be of use to you.
